.TH false 1 "December 2014" "stdutils 0.1.1" "User Command"
.SH NAME
false - Returns false (non-zero) successfully
.SH SYNOPSIS
.B false
.R [options]
.SH DESCRIPTION
The
.B false
.R utility returns false (non-zero) successfully.
.SH OPTIONS
There are currently three options supported by this implementation of true:
.IP -h
Print a help/usage screen listing these options.
.IP -?
Same as
.B -h
.IP -V
Prints version information.
.SH AUTHOR
Alan Potteiger <alanpotteiger@gmail.com>
